services:
  app:
    image: 24601/event_booking_php:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_booking_php
    working_dir: /var/www/html
    env_file:
      - ./config/DockerSecrets/app.env
    depends_on:
      - db
    networks:
      - internal

  web:
    image: nginx:latest
    container_name: event_booking_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./tmp/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./tmp/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "8443:443"
    depends_on:
      - app
    networks:
      - internal
      - frontend

  db:
    image: postgres:latest
    container_name: event_booking_db
    env_file:
      - ./config/DockerSecrets/db.env
    volumes:
      - event_pg_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  event_pg_data:

networks:
  internal:
    driver: bridge
    internal: true
  frontend:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 10.3.90.1/24

#  podman network create --driver bridge --disable-dns --internal eventbookingbackend_internal
#  podman network create --driver bridge --subnet 10.3.100.0/24 eventbookingbackend_frontend
