x-backend-build: &backend-build
  context: .
  dockerfile: Dockerfile
  args:
    PHP_VERSION: "8.5"

x-backend-service: &backend-service
  build: *backend-build
  working_dir: /var/www/html
  env_file:
    - ./.env.compose
  depends_on:
    - db
  networks:
    - internal
    - frontend

services:
  app:
    image: 24601/event_booking_php:latest
    <<: *backend-service
    container_name: event_booking_php

  assets:
    profiles: [ "assets" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.5"
    container_name: event_booking_assets
    working_dir: /var/www/html
    env_file:
      - ./.env.compose
    command: [ "composer", "run", "theme-build" ]
    volumes:
      - .:/var/www/html
      - ../district-styles:/var/www/district-styles:ro

  web:
    image: nginx:latest
    container_name: event_booking_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./tmp/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./tmp/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "8443:443"
    depends_on:
      - app
    networks:
      - internal
      - frontend

  db:
    image: postgres:latest
    container_name: event_booking_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - event_pgres_data:/var/lib/postgresql
    networks:
      - internal

  worker:
    <<: *backend-service
    container_name: event_booking_worker
    command: [ "php", "bin/cake.php", "QueueWorker" ]
    restart: always

  deploy:
    profiles: [ "deploy" ]
    container_name: event_booking_deploy
    <<: *backend-service
    command: [ "sh", "bin/deploy.sh" ]
    environment:
      CREATE_TEST_SCHEMA: ${CREATE_TEST_SCHEMA:-false}

volumes:
  event_pgres_data:

networks:
  internal:
    driver: bridge
    internal: true
  frontend:
    driver: bridge
    internal: false
#    ipam:
#      config:
#        - subnet: 10.3.90.1/24

#  podman network create --driver bridge --disable-dns --internal eventbookingbackend_internal
#  podman network create --driver bridge --subnet 10.3.100.0/24 eventbookingbackend_frontend
