apiVersion: batch/v1
kind: CronJob
metadata:
  name: event-booking-deploy
  namespace: event-booking
  labels:
    app: event-booking-deploy
spec:
  schedule: "0 3 * * 0"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: event-booking-deploy
        spec:
          serviceAccountName: event-booking-runtime
          restartPolicy: Never
          containers:
            - name: deploy
              image: ghcr.io/lbdistrictscouts/eventbookingbackend:latest
              imagePullPolicy: Always
              command:
                - sh
                - bin/deploy.sh
              env:
                - name: CREATE_TEST_SCHEMA
                  value: "false"
                - name: DISTRICT_CORE_DATA_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: event-booking-district-core-data-secrets
                      key: BASIC_AUTH_USER
                - name: DISTRICT_CORE_DATA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: event-booking-district-core-data-secrets
                      key: BASIC_AUTH_PASSWORD
              envFrom:
                - configMapRef:
                    name: event-booking-config
                - secretRef:
                    name: event-booking-secrets
