apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: event-booking-secrets
  namespace: event-booking
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/Infrastructure/items/EventBooking
