apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: event-booking
spec:
  storageClassName: local-db-ssd-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
